// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lmdfygbklncphmmmarqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxtZGZ5Z2JrbG5jcGhtbW1hcnF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNTMzODIsImV4cCI6MjA2NTcyOTM4Mn0.iqap5UPgUhI-9cEB6GoN0bE6QU33fQzhLzxATDKe-DQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);